apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awsmanagedroles.aws.managed.openshift.io
spec:
  group: aws.managed.openshift.io
  names:
    kind: AWSManagedRole
    listKind: AWSManagedRoleList
    plural: awsmanagedroles
    singular: awsmanagedrole
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AWSManagedRole is the Schema for the awsmanagedroles API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: 'AWSManagedRoleSpec defines the desired state of AWSManagedRole
            Important: Run "operator-sdk generate k8s" to regenerate code after modifying
            this file'
          properties:
            awsCustomPolicy:
              description: AWSCustomPolicy is the definition of a custom aws permission
                policy that will be associated with this role AWSCustomPolicy struct
                is defined in AWSManagedRole Types
              properties:
                awsStatements:
                  items:
                    description: StatementEntry is the smallest gourping of permissions
                      required to create an aws policy
                    properties:
                      action:
                        items:
                          type: string
                        type: array
                      condition:
                        description: Condition contains the aws Condition map to use
                          for IAM roles
                        properties:
                          StringEquals:
                            additionalProperties:
                              type: string
                            description: A map of the condition
                            type: object
                        type: object
                      effect:
                        type: string
                      principal:
                        description: Principal  contains the aws account id for the
                          principle entity of a role
                        properties:
                          AWS:
                            description: aws account id
                            items:
                              type: string
                            type: array
                        required:
                        - AWS
                        type: object
                      resource:
                        items:
                          type: string
                        type: array
                    required:
                    - action
                    - effect
                    type: object
                  type: array
                description:
                  type: string
                name:
                  type: string
              required:
              - awsStatements
              - description
              - name
              type: object
            awsManagedPolicies:
              description: AWSManagedPolicies is a list of amazong managed policies
                that exist in aws
              items:
                type: string
              type: array
            description:
              description: Description - The description of the role and policy (if
                created) that will appear in the customer's account
              type: string
          required:
          - description
          type: object
        status:
          description: AWSManagedRoleStatus defines the observed state of AWSManagedRole
          properties:
            conditions:
              items:
                description: AWSManagedRoleCondition is a Kubernetes condition type
                  for tracking AWS Managed Role status changes
                properties:
                  lastProbeTime:
                    description: LastProbeTime is the last time we probed the condition.
                    format: date-time
                    type: string
                  lastTransitionTime:
                    description: LastTransitionTime is the laste time the condition
                      transitioned from one status to another.
                    format: date-time
                    type: string
                  message:
                    description: Message is a human-readable message indicating details
                      about last transition.
                    type: string
                  reason:
                    description: Reason is a unique, one-word, CamelCase reason for
                      the condition's last transition.
                    type: string
                  status:
                    description: Status is the status of the condition
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            state:
              description: AWSManagedRoleState defines the various status an AWSManagedRole
                can have
              type: string
          required:
          - conditions
          - state
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
